# Java — job type c8jw-java (env JOB_TYPE). Obraz / StatefulSet / app: c8jw-java
apiVersion: v1
kind: Service
metadata:
  name: c8jw-java-headless
  namespace: c8-tutorial-workers
  labels:
    app: c8jw-java
spec:
  clusterIP: None
  selector:
    app: c8jw-java
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: c8jw-java
  namespace: c8-tutorial-workers
  labels:
    app: c8jw-java
    app.kubernetes.io/component: java
spec:
  serviceName: c8jw-java-headless
  replicas: 1
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: c8jw-java
  template:
    metadata:
      labels:
        app: c8jw-java
        app.kubernetes.io/component: java
    spec:
      containers:
        - name: worker
          image: europe-west3-docker.pkg.dev/my-camunda8-project/c8-tutorial-docker/c8jw-java:latest
          imagePullPolicy: Always
          env:
            - name: ZEEBE_ADDRESS
              value: camunda-platform-zeebe-gateway.camunda.svc.cluster.local:26500
            - name: JOB_TYPE
              value: c8jw-java
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
